In [3]:
import numpy as np
import pandas as pd

In [4]:
class ANN:

    def __init__(self, epochs=300, learning_rate = 0.0001):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.w_layer1 = np.ones((2, 2)) * 0.1
        self.b_layer1 = np.zeros((2, 1))
        self.w_layer2 = np.ones((2, 1)) * 0.1
        self.b_layer2 = np.zeros((1, 1))


    def activation(self, X):
        return X
        
    def fit(self, X, y):

        for i in range(self.epochs):
            for j in range(X.shape[0]):
                idx = np.random.randint(0, X.shape[0])
                
                s = X[idx].reshape((1, 2))
                o1 = self.activation(np.dot(self.w_layer1.T, s.T) + self.b_layer1)
                y_pred = self.predict(s)
                self.w_layer1 = self.w_layer1 -  self.learning_rate * (-2) * (y[idx] - y_pred) * (np.dot(s.T, self.w_layer2.T))
                self.b_layer1 = self.b_layer1 - self.learning_rate * (-2) * (y[idx] - y_pred) * (self.w_layer2)
                self.w_layer2 = self.w_layer2 - self.learning_rate * (-2) * (y[idx] - y_pred) * o1
                self.b_layer2 = self.b_layer2 - self.learning_rate * (-2) * (y[idx] - y_pred)


    def predict(self, X):
        out1 = self.activation(np.dot(self.w_layer1.T, X.T) + self.b_layer1)
        out2 = self.activation(np.dot(self.w_layer2.T, out1) + self.b_layer2)

        return out2
                

In [5]:
nn = ANN()

In [6]:
nn.predict(np.array([[1, 2], [2, 3], [0, 1]]))

array([[0.06, 0.1 , 0.02]])

In [7]:
IQ = np.array([90, 100, 110, 120, 130, 140])
CGPA = np.array([6.5, 7.0, 7.5, 8.0, 8.5, 9.0])
Package = np.array([4.5, 5.0, 6.0, 6.5, 7.0, 8.0])  # target in LPA

X = np.column_stack((IQ, CGPA))  # shape (2, m)
Y = Package


In [8]:
nn.fit(X, Y)

In [9]:
X

array([[ 90. ,   6.5],
       [100. ,   7. ],
       [110. ,   7.5],
       [120. ,   8. ],
       [130. ,   8.5],
       [140. ,   9. ]])

In [10]:
nn.predict(X)

array([[4.79177574, 5.31820033, 5.84462491, 6.37104949, 6.89747408,
        7.42389866]])

In [11]:
Y

array([4.5, 5. , 6. , 6.5, 7. , 8. ])