In [2]:
import numpy as np
import pandas as pd

In [65]:
df1 = pd.read_csv('LS_Group03/Class1.txt', sep=' ', header=None, names=['A', 'B'])
df2 = pd.read_csv('LS_Group03/Class2.txt', sep=' ', header=None, names=['A', 'B'])
df3 = pd.read_csv('LS_Group03/Class3.txt', sep=' ', header=None, names=['A', 'B'])

In [79]:
train_df1 = df1.sample(frac=0.75, random_state=43)
test_df1 = df1.drop(train_df1.index)

In [83]:
train_df2 = df2.sample(frac=0.75, random_state=43)
test_df2 = df2.drop(train_df1.index)

In [84]:
train_df3 = df3.sample(frac=0.75, random_state=43)
test_df3 = df3.drop(train_df1.index)

In [95]:
test = pd.concat([test_df1, test_df2, test_df3], axis = 0, ignore_index=True)
test

A        B
0    15.26800  0.65322
1    19.09200  1.54430
2    14.23600 -0.42192
3    13.15600 -0.55674
4    16.51500  0.81528
..        ...      ...
370  -2.82040 -2.14990
371  -0.73721  5.98980
372  -2.27010  0.69470
373  -2.81640  2.23000
374  -0.48128  0.55263

[375 rows x 2 columns]

In [96]:
mean1 = train_df1.mean().values
mean2 = train_df2.mean().values
mean3 = train_df3.mean().values

In [97]:
print(mean1, " ", mean2, " ", mean3)

[16.09387013 -0.06941938]   [  6.00634077 -11.97136667]   [-1.00425461  1.99334409]


In [98]:
cov1 = np.cov(train_df1.values.T)
cov2 = np.cov(train_df2.values.T)
cov3 = np.cov(train_df3.values.T)

In [99]:
print(cov1, "\n\n\n", cov2, "\n\n\n", cov3) 

[[8.66025107 3.09411816]
 [3.09411816 2.39051193]] 


 [[ 2.92778407 -1.57701163]
 [-1.57701163  4.49052177]] 


 [[1.99493805 1.56511582]
 [1.56511582 9.29967682]]


In [100]:
prior1 = prior2 = prior3 = 1/3

In [101]:
def classifier(X, mean, cov, prior):
    d = mean.size
    return prior * (1/(pow(2 * np.pi, d/2)) * pow(np.linalg.det(cov), 1/2)) * np.exp((-1/2)*(X-mean).T @ (np.linalg.inv(cov)) @ (X-mean))

def predict(X):
    p1 = np.array([classifier(x, mean1, cov1, prior1) for x in X])
    p2 = np.array([classifier(x, mean2, cov2, prior2) for x in X])
    p3 = np.array([classifier(x, mean3, cov3, prior3) for x in X])

    return np.argmax(np.array([p1, p2, p3]), axis = 0)

In [107]:
y_pred = predict(test.values)

In [108]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,