In [1]:
import numpy as np

In [2]:
dict1 = {"Boys":[72, 68, 70, 69, 74], "Girls":[63, 65, 69, 62, 61]}

In [3]:
dict1

{'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

In [4]:
list1=[{'Boys':i,'Girls':j} for i,j in zip(dict1['Boys'],dict1['Girls'])]

In [5]:
list1

[{'Boys': 72, 'Girls': 63},
 {'Boys': 68, 'Girls': 65},
 {'Boys': 70, 'Girls': 69},
 {'Boys': 69, 'Girls': 62},
 {'Boys': 74, 'Girls': 61}]

In [6]:
arr = np.random.rand(4, 3)

In [7]:
arr

array([[0.22418791, 0.93105075, 0.73629728],
       [0.89755516, 0.72442342, 0.35537983],
       [0.77681038, 0.76303267, 0.8591497 ],
       [0.37273073, 0.07128714, 0.44094652]])

In [8]:
arr.mean(axis = 1)

array([0.63051198, 0.65911947, 0.79966425, 0.29498813])

In [9]:
arr.std(axis = 1)

array([0.29811258, 0.22610761, 0.04243697, 0.1606133 ])

In [10]:
np.mean(arr, axis = 1)

array([0.63051198, 0.65911947, 0.79966425, 0.29498813])

In [11]:
np.var(arr, axis = 1)

array([0.08887111, 0.05112465, 0.0018009 , 0.02579663])

In [12]:
B = np.array([56, 48 , 22, 41, 78, 91, 24, 46, 8, 33])

In [13]:
B

array([56, 48, 22, 41, 78, 91, 24, 46,  8, 33])

In [14]:
np.argsort(B)

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5])

In [15]:
arr1  = np.random.randn(3,5)

In [16]:
arr1

array([[ 0.2732417 , -1.13408544,  0.40449432, -0.04744164,  0.85917318],
       [ 0.22479456,  1.39973639,  0.25108822,  0.08283052,  2.46914157],
       [ 1.43650549,  1.1094881 , -0.18680485,  1.18149525, -0.59817303]])

In [17]:
arr1.shape

(3, 5)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
type(arr1)

numpy.ndarray

In [20]:
arr1.reshape(5,3)

array([[ 0.2732417 , -1.13408544,  0.40449432],
       [-0.04744164,  0.85917318,  0.22479456],
       [ 1.39973639,  0.25108822,  0.08283052],
       [ 2.46914157,  1.43650549,  1.1094881 ],
       [-0.18680485,  1.18149525, -0.59817303]])

In [21]:
arr2 = np.array([2, 0, np.nan, 3, np.nan, 0, 7])

In [22]:
arr2

array([ 2.,  0., nan,  3., nan,  0.,  7.])

In [23]:
arr2[arr2>0]

array([2., 3., 7.])

In [24]:
np.where(arr2 ==0)[0]

array([1, 5])

In [25]:
np.argwhere(arr2==0)

array([[1],
       [5]])

In [26]:
np.argwhere(np.isnan(arr2))


array([[2],
       [4]])

In [27]:
np.where(np.isnan(arr2))

(array([2, 4]),)

In [28]:
np.where(arr2>0)[0]

array([0, 3, 6])

In [29]:
n = input("Enter the value of n: ")

Enter the value of n:  3


In [30]:
import pandas as pd

In [31]:
df = pd.DataFrame(np.random.randint(1, 100, size = (50, 3)))

In [32]:
df

0   1   2
0   93  60   1
1   71  45  60
2    4  26  58
3   49  57  48
4   38  43  61
5   69  95  32
6   72   4  22
7   67  40   3
8   87   8  42
9   36  31  75
10  50  88  29
11  84   8  36
12  23  13  49
13  52  95  29
14  74  44  91
15  96  95  94
16  26  59  13
17  49  89  37
18  33   1  67
19  29  58  36
20   4   3  92
21  32  74  94
22  40   7   5
23  27  55  25
24  38  44  87
25  30  90  29
26  26  85  99
27   8  74  58
28  88  46  27
29  11  21  16
30  41   7  91
31  91  62  72
32  97  72   6
33  30  76   7
34  43  36  58
35  23  27  65
36  93   5  74
37  31  48  27
38  89  14  31
39  36  70  94
40  90  49  91
41  22  14  89
42  45  45  12
43  10  18  11
44  51  76  98
45  15  81  21
46  25  68   3
47  46  27  49
48  40   4  10
49  37  72  57

In [ ]:
import random

In [33]:
null_row = random.sample(range(0, 50), 15)
null_row

NameError: name 'random' is not defined

In [ ]:
null_column = np.random.randint(0, 3, 15)
null_column

In [ ]:
import random

In [ ]:
random.sample(range(1, 10) ,9)

In [ ]:
index = list(zip(null_row, null_column))
for i, j in index:
    df.iloc[i, j] = np.nan
    print(i, j)

In [ ]:
df

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.isnull().sum().sum()

In [ ]:
df.dropna(axis = 1, thresh=45)

In [ ]:
df.sum(axis = 1).max()

In [ ]:
max_row = df.sum(axis = 1).idxmax()

In [ ]:
max_row

In [ ]:
df.iloc[16, :]

In [ ]:
df = df.drop(max_row, axis = 0)

In [ ]:
df

In [ ]:
df[0].shape

In [ ]:
df.sort_values(by = 0) 

In [ ]:
df.drop_duplicates(subset = 0, keep = "first")

In [ ]:
df[0].value_counts()

In [ ]:
df[0].where(df[0] == 19).value_counts()

In [ ]:
df.plot.box()

In [ ]:
correlation = df[0].corr(df[1])
correlation

In [ ]:
covariance = df[0].cov(df[1])

In [ ]:
covariance

In [ ]:
df1 = pd.cut(df[1], bins=5).head()

In [ ]:
df1