In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
X, y = load_diabetes(return_X_y=True)

In [4]:
#STOCHASTIC GRADIENT DESCENT IMPLEMENTATION

In [5]:
class SGDRegressor:
    def __init__(self, learning_rate = 0.01, epochs = 30):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.m = np.ones(X.shape[1])
        self.b = 0

    def fit(self, X, y):
        for i in range(self.epochs):
            for j in range(X.shape[0]):
                idx = np.random.randint(0, X.shape[0])
                self.b = self.b - self.learning_rate*(-2*(y[idx]-np.dot(X[idx], self.m)-self.b))
                self.m = self.m - self.learning_rate*(-2*np.dot((y[idx]-np.dot(X[idx], self.m)-self.b), X[idx]))
    def predict(self, X_test):
        return np.dot(X_test, self.m)+self.b

In [6]:
X.shape

(442, 10)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [8]:
lr = LinearRegression()

In [9]:
lr.fit(X_train, y_train)

LinearRegression()

In [10]:
lr.predict(X_test)

array([ 99.48235947, 181.25429903, 106.61572846, 123.10541923,
       183.04909567,  83.29913847, 130.54854188, 233.85654301,
       155.00942627, 171.46626454, 171.06003791, 192.94190885,
       147.25129841, 214.5307459 ,  47.50252863, 142.43786422,
       119.95723033, 209.7179434 , 185.71531692, 147.23625586,
       150.40785093, 102.60018559, 170.78899034, 177.8219416 ,
       152.40388316, 187.08466299, 197.72314739, 204.83066546,
       132.09655487, 158.42112429, 260.54948673, 125.48180691,
       195.29165994, 125.76882485, 163.21646899,  58.37895843,
       158.14323269, 103.4034084 , 128.04980829, 161.3128156 ,
       146.00080757, 219.57659671, 126.64096152, 131.12134464,
       150.1627216 ,  92.3404223 , 120.10323463, 261.33608538,
       150.22171365, 197.82772808, 145.97361477, 104.56119742,
       139.47230609, 192.90101701, 159.2347891 , 135.21956019,
       120.30423162, 262.94731714, 255.46123067, 151.24338655,
       153.11282489, 128.59191597,  69.02540213, 136.99

In [11]:
sgd = SGDRegressor(0.01, 2000)

In [12]:
sgd.fit(X_train, y_train)

In [13]:
sgd.predict(X_test)

array([100.88842567, 182.07411048, 108.45556714, 123.14791297,
       182.29747738,  84.05809107, 134.44780903, 234.88802492,
       152.6365908 , 171.43186273, 170.72353265, 191.97307729,
       147.14020908, 235.20085138,  42.73192489, 146.18534186,
       121.03480548, 209.09846871, 186.59676521, 146.57957064,
       151.05704795, 102.92289269, 171.7557036 , 175.45122211,
       153.58490901, 183.58982915, 201.60236633, 205.15880043,
       130.79476511, 162.45298094, 263.90967014, 124.61100552,
       194.58821082, 125.28330075, 163.52791417,  63.22816263,
       157.23966033, 102.07406789, 126.71391681, 163.52718701,
       146.92774689, 218.07247739, 127.61444833, 130.40022873,
       155.13925926,  95.63648215, 119.47197363, 261.7962701 ,
       150.98912954, 196.21520703, 142.30025607, 108.41612245,
       139.42556257, 192.96228334, 164.46120251, 137.29619335,
       120.95388127, 268.23895271, 256.09075357, 152.16871146,
       153.93838927, 128.74078516,  77.82282831, 139.54

In [14]:
#STOCHASTIC GRADIENT DESCENT IN SKLEARN

In [15]:
from sklearn.linear_model import SGDRegressor

In [16]:
reg = SGDRegressor(max_iter = 1000, learning_rate = 'constant', eta0 = 0.01)

In [17]:
reg.fit(X_train, y_train)

SGDRegressor(learning_rate='constant')

In [18]:
reg.predict(X_test)

array([112.50141144, 167.19390078, 116.73482448, 138.84716947,
       185.28362894, 101.58414208, 137.63369147, 210.04285415,
       160.50048615, 154.96501443, 164.73120248, 169.24384858,
       143.91682034, 235.35256114,  55.54032627, 147.19024005,
       116.1814563 , 187.19665893, 176.73602787, 136.77785165,
       149.65307453,  99.09149249, 170.75432663, 179.13662489,
       172.26860748, 179.8499032 , 185.4790285 , 192.95007268,
       131.82748375, 180.97042196, 257.51530883, 136.49304662,
       195.45706205, 137.92596376, 159.95268908,  66.76093647,
       152.8966664 ,  91.49487034, 130.26825671, 178.50103204,
       138.86909526, 211.01702048, 137.73495694, 130.33676058,
       146.76478352,  98.88851534, 129.82419986, 242.97930816,
       131.58927177, 183.87204829, 132.81069977, 115.48404437,
       137.56235375, 189.14304349, 163.16862913, 148.95529106,
       125.22093168, 240.65785915, 223.75317546, 157.85524448,
       137.97633574, 141.18166312,  87.55755734, 148.44

In [19]:
X_train

array([[ 0.06713621, -0.04464164, -0.06117437, ..., -0.03949338,
        -0.0561531 , -0.05906719],
       [-0.05273755, -0.04464164, -0.01267283, ..., -0.00259226,
        -0.02712902, -0.05078298],
       [-0.05273755, -0.04464164, -0.05578531, ...,  0.03430886,
         0.13237579,  0.00306441],
       ...,
       [-0.01277963, -0.04464164,  0.06061839, ...,  0.03430886,
         0.07020738,  0.00720652],
       [-0.03457486,  0.05068012, -0.00081689, ...,  0.1081111 ,
         0.02671684,  0.07348023],
       [ 0.01991321,  0.05068012,  0.10480869, ..., -0.00259226,
         0.00370906,  0.04034337]], shape=(353, 10))

In [25]:
X_train[0].reshape((1, 10))

array([[ 0.06713621, -0.04464164, -0.06117437, -0.04009893, -0.02633611,
        -0.02448686,  0.03391355, -0.03949338, -0.0561531 , -0.05906719]])

In [26]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Generate synthetic data with 2 input features
X, y = make_regression(n_samples=100, n_features=2, noise=10, random_state=42)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print results
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)
print("Model Coefficients:", model.coef_)
print("Model Intercept:", model.intercept_)

Mean Squared Error: 154.62772689490527
R-squared Score: 0.9836279308340317
Model Coefficients: [86.31018533 73.66927906]
Model Intercept: 0.06595480364319961


In [27]:
X

array([[-1.1913035 ,  0.65655361],
       [ 0.05820872, -1.1429703 ],
       [ 0.58685709,  2.19045563],
       [ 0.47323762, -0.07282891],
       [ 0.73846658,  0.17136828],
       [-0.88951443, -0.81581028],
       [-1.91877122, -0.02651388],
       [-0.44651495,  0.85639879],
       [ 0.81252582,  1.35624003],
       [ 1.14282281,  0.75193303],
       [-1.10633497, -1.19620662],
       [ 0.62566735, -0.85715756],
       [-0.60063869, -0.29169375],
       [-0.39210815, -1.46351495],
       [-0.23415337, -0.23413696],
       [-0.84679372, -1.51484722],
       [ 0.91540212,  0.32875111],
       [ 0.32408397, -0.38508228],
       [ 0.09707755,  0.96864499],
       [-0.07201012,  1.0035329 ],
       [-0.46341769, -0.46572975],
       [-1.06230371,  0.47359243],
       [ 1.57921282,  0.76743473],
       [ 0.01300189,  1.45353408],
       [-0.91942423,  1.54993441],
       [-0.21967189,  0.35711257],
       [ 0.00511346, -0.23458713],
       [-1.32818605,  0.19686124],
       [-0.11564828,

In [28]:
y

array([ -49.26502323,  -85.16238696,  211.22565822,   29.19656159,
         84.34809556, -132.59309441, -177.38857889,   27.3363108 ,
        193.19427371,  155.37378211, -192.1940877 ,  -14.4948211 ,
        -82.03443098, -138.76529089,  -51.66481124, -177.51453029,
        101.32275496,  -10.86887986,   73.73821152,   74.35978383,
        -70.02095954,  -62.52187111,  186.02678587,  106.7327714 ,
         35.45387597,   12.23023148,   -7.75021827, -120.62125675,
        -48.57864443,   44.16868914, -140.32938873,   50.03381879,
       -154.46482643,  -41.76089202, -134.11934105,  173.57870762,
        180.18574091,  -21.23329068,  -31.0566576 ,  136.43187681,
       -115.35020121, -160.44108941,  -78.88195313, -172.93095692,
         69.78403702,  -34.16137734,  -68.2138891 ,  -17.44964928,
        121.40729411, -120.10660283, -103.83983438,  -12.22864097,
        -36.31090174,    4.15107961,  -55.33877326,  -65.5648547 ,
        193.11293839,   13.20678827,   99.93216442, -145.27351